name: Update Trakt Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write
  secrets: write

jobs:
  update-trakt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Generate Trakt SVG
        id: generate_svg
        env:
          TRAKT_USERNAME: ${{ secrets.TRAKT_USERNAME }}
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          TRAKT_CLIENT_SECRET: ${{ secrets.TRAKT_CLIENT_SECRET }}
          TRAKT_CREDENTIALS: ${{ secrets.TRAKT_CREDENTIALS }}
        run: python update_trakt_stats.py

      - name: Update secret if token was refreshed
        if: steps.generate_svg.outputs.refreshed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh secret set TRAKT_CREDENTIALS --body "$(cat refreshed_credentials.json)"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add trakt_stats.svg logo.*
          git diff --quiet && git diff --staged --quiet || git commit -m "CHORE: Update Trakt watch history"
          git push

